v0.0.1
eastgenomics/eggd_GATKgCNV_call pull request #1
Opened 2022-05-05 12:05 UTC by sophie22

Initial PR for a working version of the CNV calling applet using GATK 4.2.5.0 for the germline CNV calling workflow.

2022-05-05 12:05 UTC, pep8speaks commented
Hello @sophie22! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/generate_gcnv_bed.py`](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py):

> [Line 51:80](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L51): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 86:13](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L86): [E722](https://duckduckgo.com/?q=pep8%20E722) do not use bare 'except'
> [Line 133:9](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L133): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 134:9](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L134): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 135:5](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L135): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> [Line 138:5](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L138): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 179:80](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L179): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 188:80](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L188): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 208:1](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L208): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1

* In the file [`resources/home/dnanexus/summarise_calls.py`](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py):

> [Line 61:9](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L61): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 62:9](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L62): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 75:25](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L75): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented (comment)
> [Line 76:80](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L76): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 97:80](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L97): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 123:17](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L123): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 146:9](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L146): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 178:17](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L178): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 196:33](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L196): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 203:21](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L203): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 205:9](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L205): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 207:80](https://github.com/eastgenomics/eggd_GATKgCNV_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L207): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)

2022-05-10 06:59 UTC, mattgarner requested changes
> Reviewed 15 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1)* status: 15 of 16 files reviewed, 28 unresolved discussions (waiting on @mattgarner and @sophie22)

___
*[`dxapp.json` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dewXzC8XbL4aGKD1X:-N1dewXzC8XbL4aGKD1Y:b3ldktd) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L2)):*
> ```JSON
> {
>     "name": "GATKgCNV_call_v0.0.1_dev",
> ```

Let's change this to reflect the first version



_Code quote:_
```JSON
v0.0.1_dev
```
___
*[`dxapp.json` line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dfDmvDOwLofp0LXnb:-N1dfDmvDOwLofp0LXnc:bpjum1r) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L27)):*
> ```JSON
>         {
>         "name": "bambis",
>         "label": "Bunch of sample.bam AND sample.bai files",
> ```

Should describe that these need to be paired.
Would it be better to split them into 2 separate inputs?



_Code quote:_
```JSON
Bunch of sample.bam AND sample.bai files
```
___
*[`dxapp.json` line 38 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dg72n-Qivhjf_bWDH:-N1dg72n-Qivhjf_bWDI:b-prweea) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L38)):*
> ```JSON
>         "class": "file",
>         "optional": false,
>         "patterns": ["*.bed", "*.interval_list", "*.intervals"],
> ```

Seems like this should be one of:
*.interval_list
*.list
*.bed

https://gatk.broadinstitute.org/hc/en-us/articles/360035531852-Intervals-and-interval-lists



_Code quote:_
```JSON
["*.bed", "*.interval_list", "*.intervals"],
```
___
*[`dxapp.json` line 138 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dh9S89PV5uYiPy3kD:-N1dh9S89PV5uYiPy3kE:beh8bmz) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L138)):*
> ```JSON
>         {
>         "name": "prior_prob",
>         "label": "prior probability for contigs",
> ```

Could we elaborate a little? What are the prior probabilities of?



_Code quote:_
```JSON
prior probability for contigs
```
___
*[`dxapp.json` line 146 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dhQqkDIgoVcmQgkPV:-N1dhQqlAuBuFUGlWyVC:b-onhj7n) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L146)):*
> ```JSON
>     "outputSpec": [
>         {
>         "name": "result_files",
> ```

Would we ever need to send subsets of these files to downstream apps? Does it make sense to split them into multiple outputs?



_Code quote:_
```JSON
    "outputSpec": [
        {
        "name": "result_files",
        "label": "sample CNV vcfs, copy ratio files and run-level annotation and visualisation files",
        "class": "array:file"
        }
```
___
*[`dxapp.json` line 159 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dhcgt8pRx6RC-o2f7:-N1dhcgt8pRx6RC-o2f8:bmuxdnv) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L159)):*
> ```JSON
>         "timeoutPolicy": {
>         "*": {
>             "hours": 24
> ```

Is this appropriate, or should it be reduced? 
What is our current expected runtime?



_Code quote:_
```JSON
24
```
___
*[`dxapp.json` line 166 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dhxb315_lz6OURm_P:-N1dhxb315_lz6OURm_Q:b-qfz5my) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L166)):*
> ```JSON
>             "name": "htslib",
>             "project": "project-Fkb6Gkj433GVVvj73J7x8KbV",
>             "folder": "/app_assets/htslib/htslib_v1.14.0",
> ```

Should we be using this more recent version instead?
https://platform.dnanexus.com/panx/projects/Fkb6Gkj433GVVvj73J7x8KbV/data/app_assets/htslib/htslib_v1.15.0



_Code quote:_
```JSON
"/app_assets/htslib/htslib_v1.14.0",
```
___
*[`dxapp.json` line 178 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1di9uyASlKHxt93AKP:-N1di9uyASlKHxt93AKQ:b-iqghg7) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L178)):*
> ```JSON
>     },
>     "developers":[
>         "user-sophier",
> ```

Redundant, since you are in the org



_Code quote:_
```JSON
user-sophier
```
___
*[`README.md` line 23 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1diPK2-xwmwEOCWGVf:-N1diPK3EZ8akbBrQXeP:b-gtp1yj) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/README.md#L23)):*
> ```Markdown
> ## What data are required for this app to run?
> This app requires:
> * at least 30 sample.bam and sample.bai files from the same sequencing run (array of files)
> ```

perhaps this should read

30 pairs of sample.bam and sample.bai 

so that it's not ambiguous if it's 15+15 = 30, or 30 + 30



_Code quote:_
```Markdown
30 sample.bam and sample.bai
```
___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 24 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dj6Fw2CeSTwG44yar:-N1dj6Fw2CeSTwG44yas:bwf7c44) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L24)):*
> ```Python
> def parse_args():
>     """
>         Parse command line arguments
> ```

One line docstrings like:
\`\`\`My docstring is short\`\`\`

Multiline docstrings like:
\`\`\`
My docstring
is long
\`\`\`

as per https://peps.python.org/pep-0257/ please



_Code quote:_
```Python
    """
        Parse command line arguments
    """
```
___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dql-WCl-hLISGRUTK:-N1dql-WCl-hLISGRUTL:b-8za478) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L56)):*
> ```Python
> 
> 
> def generate_bed(args):
> ```

Is this a good name for the function? 
Looks like it returns a dataframe, not a bed as the name would suggest



_Code quote:_
```Python
generate_bed
```
___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 81 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1drhNm8VCy2ZWndgF3:-N1drhNm8VCy2ZWndgF4:b2cs6q1) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L81)):*
> ```Python
> 
>             # check we haven't read in twice
>             try:
> ```

What's the scenario we are defending against here? Passing multiple input files for the same sample?
Might be better to exit rather than skip, since we don't know which one is the correct one if they are different



_Code quote:_
```Python
            try:
                assert sample_name not in copy_ratio_df.columns, (
                    f"Sample {sample_name} already in sample list!"
                    f"Current sample list: {copy_ratio_df.columns}"
                )
            except:
                print("Sample is already loaded, skipping it")
                continue
```
___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 110 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dshuN1eS3d4ysXdQ6:-N1dshuN1eS3d4ysXdQ7:b-z5g27c) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L110)):*
> ```Python
> 
> 
> def gene [...]

2022-05-10 15:00 UTC, sophie22 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1)* status: 11 of 16 files reviewed, 28 unresolved discussions (waiting on @mattgarner and @sophie22)

___
*[`dxapp.json` line 159 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dhcgt8pRx6RC-o2f7:-N1iQ3RJCp6-N6GYoIXT:b-p17ep9) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L159)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is this appropriate, or should it be reduced? 
What is our current expected runtime?
</blockquote></details>

CEN runs with 48 samples complete within 1.5 h, could set it to 2 hours for CEN, but with the Medicover data it ran for over 23h
___
*[`src/GATK_gCNVcaller.sh` line 84 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e0KMf67sNoinpam_p:-N1iS4Hs1KAUZqWir7fx:be4jkr7) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L84)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is the extension on these _basecount files variable? Does it need to be *?
</blockquote></details>

it can be tsv or hdf5. It used to be tsv so I can inspect the file contents, but according to GATK processing of hdf5 is faster and more efficient https://gatk.broadinstitute.org/hc/en-us/articles/4418054257691-CollectReadCounts
___
*[`src/GATK_gCNVcaller.sh` line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e0kMW-C4MnI6-rPc_:-N1iSdCU3DIe58wZiRaH:b3nqz8b) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L100)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Can you comment to explain what is going on here? Why +88?
</blockquote></details>

the Picard-style interval lists are a bed file with a header that is 88 lines long. bedtools can't directly process Picard-style interval lists but by skipping the header it looks just like a bed file
___
*[`src/GATK_gCNVcaller.sh` line 101 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e0qh_5IZ0c_P6z6XY:-N1iSzwd7dv7HvAJX2Pb:bouk3lw) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L101)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Does this have a purpose? We don't capture the output or do anything with it
</blockquote></details>

it was used during dev to check that file is not empty
___
*[`src/GATK_gCNVcaller.sh` line 190 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e3YxA6N-y0CsSNow_:-N1iTClWEyn0cCFg8Pkz:b-axpqak) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L190)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Can this be deleted?
</blockquote></details>

if we no longer want to use these files then yes
___
*[`src/GATK_gCNVcaller.sh` line 195 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e3dWm8UH9Ko0aBarX:-N1iTJTjCEp8ll8-UtK4:bb7od0r) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L195)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

and this?
</blockquote></details>

same


<!-- Sent from Reviewable.io -->

2022-05-10 15:05 UTC, sophie22 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1)* status: 11 of 16 files reviewed, 28 unresolved discussions (waiting on @mattgarner and @sophie22)

___
*[`dxapp.json` line 178 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1di9uyASlKHxt93AKP:-N1iUXYG2eb9_lj5Ecvz:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L178)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Redundant, since you are in the org
</blockquote></details>

Done.
___
*[`README.md` line 23 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1diPK2-xwmwEOCWGVf:-N1iUZMK8Ln2utPqe2bq:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/README.md#L23)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

perhaps this should read

30 pairs of sample.bam and sample.bai 

so that it's not ambiguous if it's 15+15 = 30, or 30 + 30
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 24 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dj6Fw2CeSTwG44yar:-N1iU_TX8moJTtc4gyyl:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L24)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

One line docstrings like:
\`\`\`My docstring is short\`\`\`

Multiline docstrings like:
\`\`\`
My docstring
is long
\`\`\`

as per https://peps.python.org/pep-0257/ please
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/summarise_calls.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e4IIg9I0Z9EQLmots:-N1iUdbw1JvxFPKVxzMG:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/summarise_calls.py#L1)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

If we don't call this script from PATH as an executable then we can remove this.
If we use an updated dx instance in the future that may not use 3.8, so this might be confusing
</blockquote></details>

Done.
___
*[`src/GATK_gCNVcaller.sh` line 24 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dxeZT7COiOsJ8alvL:-N1iUfafC-kXiRlRv3cT:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L24)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Comment to explain this please
</blockquote></details>

Done.
___
*[`src/GATK_gCNVcaller.sh` line 205 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e4-nD0FzdxLqs0m0b:-N1iV7hLDCUtHHXtDkCQ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L205)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Maybe put this at the start of this block?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-10 16:16 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1)* status: 11 of 16 files reviewed, 28 unresolved discussions (waiting on @jethror1, @mattgarner, and @sophie22)

___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 24 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dj6Fw2CeSTwG44yar:-N1if6T7BxxZnMkzYO0P:bvvai3y) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L24)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

text doesn't need to be indented in a docstring
___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dql-WCl-hLISGRUTK:-N1ikEKkE697L-CyhNmq:b-dame8z) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L56)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is this a good name for the function? 
Looks like it returns a dataframe, not a bed as the name would suggest
</blockquote></details>

changed to `generate_copy_ratio_df()`
___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 81 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1drhNm8VCy2ZWndgF3:-N1ifLW00IPVjfzCDeVW:bm5gaz4) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L81)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

What's the scenario we are defending against here? Passing multiple input files for the same sample?
Might be better to exit rather than skip, since we don't know which one is the correct one if they are different
</blockquote></details>

I don't think I wrote this.... @sophie22 ? I previously had it as a bare assert, so would exit with AssertionError
___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 110 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dshuN1eS3d4ysXdQ6:-N1ikGfP-NFtKgXBcZpY:b-losfs9) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L110)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Returns a df not a bed
</blockquote></details>

changed to `generate_per_sample_copy_ratio_dfs()`
___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 160 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dt_JdCLXKLDLZRqee:-N1iiLWc58KdNSy5myph:b-9xvetx) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L160)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could this be made a little clearer? Not sure exactly what it's changing from the description here
</blockquote></details>

this is for controlling the header written to the bed file, if its per sample we add the track lines for mean and std dev, if per run then we add the clickToHighlight option.

have updated the comment
___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 188 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dvmo22P91kNQjpcTt:-N1iiY4c9Z5iENQycp60:bsw4c7u) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L188)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could we add the header lines to a list, then use the len of that list to determine how many lines to skip?
This way if we add to the header in the future we don't need to remember to update the hardcoded number of lines to skip
</blockquote></details>

the number of header lines in the bed will never be more than one as it that is what the gCNV track in igv.js requires, and if it did it would be as a direct result of changing the above lines of code and not from anywhere else since we directly write the header line to file then append the dataframe


<!-- Sent from Reviewable.io -->

2022-05-12 13:27 UTC, mattgarner requested changes
> Reviewed 2 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1)* status: 14 of 16 files reviewed, 28 unresolved discussions (waiting on @jethror1, @mattgarner, and @sophie22)

___
*[`resources/home/dnanexus/summarise_calls.py` line 31 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sOQC573oC9GgmchI0:-N1sOQC573oC9GgmchI1:b-npwnpr) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L31)):*
> ```Python
>         CNV_call['end'] = record.INFO["END"]
>         CNV_call['ID'] = record.ID  # str
>         if record.ALT[0] is None:
> ```

Is this for non-variant segments? Could we comment this?



_Code quote:_
```Python
        if record.ALT[0] is None:
            continue
```
___
*[`resources/home/dnanexus/summarise_calls.py` line 33 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sO_XuCCl45-kTfZKu:-N1sO_XuCCl45-kTfZKv:b-nkmruu) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L33)):*
> ```Python
>         if record.ALT[0] is None:
>             continue
>         CNV_call['CNV'] = str(record.ALT[0]).strip("<>")
> ```

Does a call always have one alt? If we are assuming this is the case, do we have something to catch any records where this is not the case?
If we think it never happens, then it would be OK to error out if this is seen



_Code quote:_
```Python
CNV_call['CNV'] = str(record.ALT[0]).strip("<>")
```
___
*[`resources/home/dnanexus/summarise_calls.py` line 43 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sP4aE2QaAk0RBcEaK:-N1sP4aE2QaAk0RBcEaL:b-3o6p22) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L43)):*
> ```Python
> 
> 
> def ID2pos(row):
> ```

docstring please



_Code quote:_
```Python
def ID2pos(row):
```
___
*[`resources/home/dnanexus/summarise_calls.py` line 50 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sP7mc1WVV3QEhOUEz:-N1sP7mc1WVV3QEhOUF-:bjju17a) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L50)):*
> ```Python
> def annotate(calls_df, exons_df):
>     """
>         Annotate each CNV call with overlapping exon information
> ```

Single line docstring should be formatted like
""" Text goes here """
___
*[`resources/home/dnanexus/summarise_calls.py` line 56 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sP_jE8VVy5KIFeQk-:-N1sP_jE8VVy5KIFeQk0:b-hysobl) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L56)):*
> ```Python
> 
>     # Intersecting calls bed file with transcript_exon information
>     # requires 100% overlap on exon within call coordinates
> ```

So a partially deleted exon does not get included? Is this the behaviour we want?



_Code quote:_
```Python
    # Intersecting calls bed file with transcript_exon information
    # requires 100% overlap on exon within call coordinates
```
___
*[`resources/home/dnanexus/summarise_calls.py` line 63 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sQDE289YRgx_Jgz8H:-N1sQDE289YRgx_Jgz8I:blc3bdv) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L63)):*
> ```Python
>         "exon_chrom", "exon_start", "exon_end", "gene", "transcript", "exon"])
>     annotated_calls_df['exon_length'] = \
>         annotated_calls_df['exon_end'] - annotated_calls_df['exon_start']
> ```

Does this account for 0 or 1 based coordinates?



_Code quote:_
```Python
annotated_calls_df['exon_end'] - annotated_calls_df['exon_start']
```
___
*[`resources/home/dnanexus/summarise_calls.py` line 68 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sRCrX3u-Hm2Zf1770:-N1sRCrX3u-Hm2Zf1771:b-7ilvfu) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L68)):*
> ```Python
> 
>     calls = annotated_calls_df["call_ID"].unique().tolist()
>     genes = []  # list that will become the genes column in the dfexon
> ```

typo?



_Code quote:_
```Python
dfexon
```
___
*[`resources/home/dnanexus/summarise_calls.py` line 79 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sRad6E2iRmikN-b9x:-N1sRad6E2iRmikN-b9y:b-6x9g71) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L79)):*
> ```Python
>         # print("annotation_df for sample {}, call {}".format(
>         #     calls_df["sample"][0], call))
>         if len(annotation_df) == 1:  # call is a single exon
> ```

What will be the value of `gene` when the "exon" is not actually part of a gene? e.g. a GREM1 promoter



_Code quote:_
```Python
        if len(annotation_df) == 1:  # call is a single exon
            call_gene = annotation_df["gene"][0]
```


<!-- Sent from Reviewable.io -->

2022-05-12 14:26 UTC, sophie22 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1)* status: 14 of 16 files reviewed, 28 unresolved discussions (waiting on @jethror1, @mattgarner, and @sophie22)

___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 81 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1drhNm8VCy2ZWndgF3:-N1se5bZAD_eLdIS_dfx:b-fnjhrn) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L81)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I don't think I wrote this.... @sophie22 ? I previously had it as a bare assert, so would exit with AssertionError
</blockquote></details>

It is added at this commit (from the old repo) https://github.com/eastgenomics/CNV_calling_dev/commit/828c4a6af798f2458c9f9132d0c90b9065b412f8


<!-- Sent from Reviewable.io -->

2022-05-12 15:16 UTC, sophie22 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1)* status: 13 of 16 files reviewed, 28 unresolved discussions (waiting on @jethror1, @mattgarner, and @sophie22)

___
*[`dxapp.json` line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dfDmvDOwLofp0LXnb:-N1sh6HgDd_jqJsHgWtb:bbz07v) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L27)):*
> Bunch of sample.bam AND sample.bai files
works well for now, no clear reason to split inputs
___
*[`dxapp.json` line 38 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dg72n-Qivhjf_bWDH:-N1shafj9jDT1Me7VSEq:bes7q1r) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L38)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Seems like this should be one of:
*.interval_list
*.list
*.bed

https://gatk.broadinstitute.org/hc/en-us/articles/360035531852-Intervals-and-interval-lists
</blockquote></details>

restrict to .interval_list only which is the output type from the prep step
___
*[`dxapp.json` line 138 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dh9S89PV5uYiPy3kD:-N1siZ6Q3MK2XStG6u-E:b2782mv) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L138)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could we elaborate a little? What are the prior probabilities of?
</blockquote></details>

slightly improved
___
*[`dxapp.json` line 146 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dhQqkDIgoVcmQgkPV:-N1sisFNE8UV5kC8Delg:b-jhe81e) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L146)):*
> result_files
it's okay for now
___
*[`resources/home/dnanexus/generate_gcnv_bed.py` line 24 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dj6Fw2CeSTwG44yar:-N1sjUPFBZzmwRwg6wBM:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/resources/home/dnanexus/generate_gcnv_bed.py#L24)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

text doesn't need to be indented in a docstring
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/summarise_calls.py` line 31 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sOQC573oC9GgmchI0:-N1smEa0BtLRl-P1axgz:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L31)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is this for non-variant segments? Could we comment this?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/summarise_calls.py` line 50 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sP7mc1WVV3QEhOUEz:-N1smHTd0BzuL4lqGd25:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L50)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Single line docstring should be formatted like
""" Text goes here """
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/summarise_calls.py` line 63 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sQDE289YRgx_Jgz8H:-N1smVQR7taLO_L5PaCE:b-tffkt1) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L63)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Does this account for 0 or 1 based coordinates?
</blockquote></details>

0-based as that is what's used in exons_nirvana


<!-- Sent from Reviewable.io -->

2022-05-12 15:44 UTC, sophie22 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1)* status: 13 of 16 files reviewed, 28 unresolved discussions (waiting on @jethror1, @mattgarner, and @sophie22)

___
*[`dxapp.json` line 2 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dewXzC8XbL4aGKD1X:-N1srMwx8SuM-c9Qg936:b-ez265j) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L2)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Let's change this to reflect the first version
</blockquote></details>

will do closer to releasing
___
*[`dxapp.json` line 138 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dh9S89PV5uYiPy3kD:-N1srUrA21d0YXBxvfeZ:b-vpzi3k) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L138)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

slightly improved
</blockquote></details>

added "help" description
___
*[`resources/home/dnanexus/summarise_calls.py` line 68 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sRCrX3u-Hm2Zf1770:-N1svma68OSAJIPXCO7q:b-yigp24) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L68)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

typo?
</blockquote></details>

corrected


<!-- Sent from Reviewable.io -->

2022-05-13 10:19 UTC, sophie22 reviewed
> Reviewed 1 of 1 files at r3, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1)* status: 15 of 16 files reviewed, 28 unresolved discussions (waiting on @jethror1, @mattgarner, and @sophie22)

___
*[`dxapp.json` line 166 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dhxb315_lz6OURm_P:-N1wuosB1gxYLJA1vcry:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L166)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should we be using this more recent version instead?
https://platform.dnanexus.com/panx/projects/Fkb6Gkj433GVVvj73J7x8KbV/data/app_assets/htslib/htslib_v1.15.0

</blockquote></details>

Done.
___
*[`src/GATK_gCNVcaller.sh` line 72 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dzjFEBKTUOabbhbB5:-N1worgo3PqrT31QN9w9:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L72)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

No longer required?
</blockquote></details>

Done.
___
*[`src/GATK_gCNVcaller.sh` line 82 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e09Dy5E0clYavPUXF:-N1wv8yu17HjKpRzD39z:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L82)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Is the use of both inputs/base_counts and data/base_counts here intentional?
</blockquote></details>

Done.
___
*[`src/GATK_gCNVcaller.sh` line 100 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e0kMW-C4MnI6-rPc_:-N1wvAq4Bi-7DC5c5w3N:bz67zjf) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L100)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

the Picard-style interval lists are a bed file with a header that is 88 lines long. bedtools can't directly process Picard-style interval lists but by skipping the header it looks just like a bed file
</blockquote></details>

thanks for the improved way of handling header lines
___
*[`src/GATK_gCNVcaller.sh` line 142 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e1Wic5xaQZK_GbsUn:-N1wvIBG47ZaUkQehlHp:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L142)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should this be removed?
</blockquote></details>

Done.
___
*[`src/GATK_gCNVcaller.sh` line 168 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e25g239hogOzcFEsy:-N1wvLPeBTyvS1aSbvDm:bpx1kec) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L168)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Comments here would be good. 
Why do we need sample number and index, how are they used? What is parallel doing?
</blockquote></details>

Added comments + discussion
___
*[`src/GATK_gCNVcaller.sh` line 184 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e3Pk45vK9w9rjazU0:-N1wvPkS-peaUfShEyTi:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L184)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should we include more mark sections to describe what we are doing downstream from here?
</blockquote></details>

Done.
___
*[`src/GATK_gCNVcaller.sh` line 190 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e3YxA6N-y0CsSNow_:-N1wvR6wCANh9_N5cX-B:bb7f2mf) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L190)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

if we no longer want to use these files then yes
</blockquote></details>

done
___
*[`src/GATK_gCNVcaller.sh` line 195 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1e3dWm8UH9Ko0aBarX:-N1wvScu3Qj7t5LXxhqJ:bb7f2mf) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/src/GATK_gCNVcaller.sh#L195)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

same
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-05-13 10:31 UTC, mattgarner reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1)* status: 15 of 16 files reviewed, 9 unresolved discussions (waiting on @jethror1, @mattgarner, and @sophie22)

___
*[`dxapp.json` line 146 at r1](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1dhQqkDIgoVcmQgkPV:-N1wxUsICdlLBdL9peZL:b1300by) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/a7d121558bc487ff0fc4f61a7f089551e5738dff/dxapp.json#L146)):*
<details><summary><i>Previously, sophie22 wrote…</i></summary><blockquote>

> result_files
it's okay for now
</blockquote></details>

No need right now - no obvious use for splitting. Will split later if there is demand for this


<!-- Sent from Reviewable.io -->

2022-05-13 11:35 UTC, sophie22 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1)* status: 13 of 16 files reviewed, 9 unresolved discussions (waiting on @jethror1, @mattgarner, and @sophie22)

___
*[`resources/home/dnanexus/summarise_calls.py` line 33 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sO_XuCCl45-kTfZKu:-N1xBgR6A43R34BvJupA:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L33)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Does a call always have one alt? If we are assuming this is the case, do we have something to catch any records where this is not the case?
If we think it never happens, then it would be OK to error out if this is seen
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/summarise_calls.py` line 43 at r3](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1#-N1sP4aE2QaAk0RBcEaK:-N1xBqPiEZJcJ4lyu6I2:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_gatkgcnv_call/blob/82e6f577438ace5963d912e9dc9f1c012febb4b0/resources/home/dnanexus/summarise_calls.py#L43)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

docstring please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-18 10:35 UTC, mattgarner approved these changes
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_gatkgcnv_call/1)* status: all files reviewed, 1 unresolved discussion (waiting on @sophie22)



<!-- Sent from Reviewable.io -->

2022-05-23 15:02 UTC, merged